# Generated by Django 5.1.5 on 2025-01-24 18:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_user_is_admin_alter_user_email_alter_user_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bio', models.CharField(max_length=255, null=True, verbose_name='Biography')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('profile_pic', models.ImageField(null=True, upload_to='profile_pictures/', verbose_name='Profile Picture')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Last Login')),
                ('social_links', models.JSONField(null=True, verbose_name='Social Links')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
