# Generated by Django 5.1.5 on 2025-01-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='location',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
    ]
