# Generated by Django 5.1.5 on 2025-01-21 19:00

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(255)], verbose_name='First Name')),
                ('last_name', models.CharField(validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(255)], verbose_name='Last Name')),
                ('username', models.CharField(validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(255)], verbose_name='Username')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(255)], verbose_name='Email')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(1)], verbose_name='Gender')),
                ('password', models.CharField(validators=[django.core.validators.MinLengthValidator(8), django.core.validators.MaxLengthValidator(255)], verbose_name='Password')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
