# Generated by Django 5.1.5 on 2025-01-22 10:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_token',
            field=models.CharField(null=True, validators=[django.core.validators.MaxLengthValidator(64)], verbose_name='Reset Token'),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_token_expiration',
            field=models.DateTimeField(null=True, verbose_name='Reset Token Expiration'),
        ),
    ]
