# Generated by Django 5.1.5 on 2025-01-25 12:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_is_admin_alter_user_email_alter_user_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
