# Generated by Django 5.1.5 on 2025-01-25 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_friend_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friend_list',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
